name: MikuDreamCore
version: '1.2.200'
main: cn.mikudream.core.MikuDream
api-version: '1.21'
authors: [onea]
folia-supported: true
soft-depend: []
website: https://cysunk.mlzi.top/
commands:
  hub:
    description: hub
  skill:
    description: skill
  sconfig:
    description: config
  sbreakboard:
    description: off & on the breakboard
  coin:
    description: coin
  sv:
    description: sv
  srf:
    description: srf
  svold:
    description: svold
  shop:
    description: shop
  friend:
    description: friend


permissions:
  mikucore.config:
    description: config
    default: op
  mikucore.breakboard:
    description: breakboard
    default: true
  mikucore.sv:
    description: sv
    default: op

  coin.commands:
    description: 使用scoin命令的总权限
    default: true
  coin.list:
    description: 使用list子命令
    default: true
  coin.add:
    description: 使用add子命令
    default: op
  coin.version:
    description: 使用version子命令
    default: true
  coin.reload:
    description: 使用reload子命令
    default: op
  coin.remove:
    description: 使用remove子命令
    default: op

  shop.commands:
    description: shop
    default: true
  shop.list:
    description: 使用list子命令
    default: true
  shop.buy:
    description: 使用buy子命令
    default: true
  shop.sell:
    description: 使用sell子命令
    default: true


  friend.commands:
    description: friend
    default: true
  friend.list:
    description: 使用list子命令
    default: true
  friend.add:
    description: 使用add子命令
    default: true
  friend.remove:
    description: 使用remove子命令
    default: true
  friend.accept:
    description: 使用accept子命令
    default: true
