name: catplugin
version: '1.0.5'
main: cn.onea.catplugin.CatPlugin
api-version: '1.21'
authors: [onea]
commands:
  hub:
    description: hub
    usage: /<command>
  catkill:
    description: catkill
    usage: /<command>
  catconfig:
    description: catkill
    usage: /<command>
permissions:
  cat.admin:
    description: 管理功能喵
    default: op
