name: Redstone
version: '1.0.12'
main: cn.mikudream.core.MikuDream
api-version: '1.21'
authors: [onea]
folia-supported: true
soft-depend: [ProtocolLib]
website: https://github.com/oneachina/SunkPlugin
commands:
  hub:
    description: hub
  skill:
    description: skill
  sconfig:
    description: sconfig
  sbreakboard:
    description: off & on the breakboard
    usage: /sbreakboard

permissions:
  sunk.config:
    description: config
    default: op
  sunk.breakboard:
    description: breakboard
    default: true
