name: SunkPlugins
version: '1.1.8'
main: cn.onea.sunkplugin.SunkPlugins
api-version: '1.21'
authors: [onea]
folia-supported: true
soft-depend: [ProtocolLib,TheNewEconomy]
website: https://github.com/oneachina/SunkPlugin
commands:
  hub:
    description: hub
  skill:
    description: skill
  sconfig:
    description: sconfig
  sraffle:
    description: sraffle
  v:
    description:
      a gemini command
  vanish:
    description:
      a gemini command
  sc:
    description: 管理sunk币
    usage: /sc <玩家> <add/del> <数量> 或 /sc list [玩家]
  sunkcoin:
      description: 管理sunk币
      usage: /sunkcoin <玩家> <add/del> <数量> 或 /sunkcoin list [玩家]
  sop:
    description: 回档后恢复OP权限
    usage: /sop <玩家ID>

permissions:
  sunk.config:
    description: 管理功能喵
    default: op
  sunk.vanish:
    default: op
    description: vanish
  sunk.raffle.admin:
    description: 允许无限抽奖
    default: op
  sunk.sop:
    description: 回档专用
    default: op  # 仅限OP使用此命令
  sunk.coin.admin:
    description: 允许管理sunk币
    default: op
