name: SunkPlugins
version: '1.0.7'
main: cn.onea.sunkplugin.SunkPlugins
api-version: '1.21'
authors: [onea]
soft-depend: [ProtocolLib]
website: https://github.com/oneachina/SunkPlugin
commands:
  hub:
    description: hub
    usage: /<command>
  catkill:
    description: catkill
    usage: /<command>
  catconfig:
    description: catconfig
    usage: /<command>
  raffle:
    description: raffle
    usage: /<command>

permissions:
  cat.admin:
    description: 管理功能喵
    default: op
