name: SunkPlugins
version: '1.1.0'
main: cn.onea.sunkplugin.SunkPlugins
api-version: '1.21'
authors: [onea]
folia-supported: true
soft-depend: [ProtocolLib]
website: https://github.com/oneachina/SunkPlugin
commands:
  hub:
    description: hub
  skill:
    description: skill
  sconfig:
    description: sconfig
  sraffle:
    description: sraffle
  v:
    description:
      a gemini command
  vanish:
    description:
      a gemini command

permissions:
  sunk.config:
    description: 管理功能喵
    default: op
  sunk.vanish:
    default: op
    description: vanish
