name: MikuDream
version: 25.12.1
main: cn.mikudream.core.MikuDream
api-version: '1.21.10'
description: A plugin for MikuDream Server

commands:
  friend:
    description: 好友系统命令
    usage: /<command> [add|remove|list|accept|deny|tp] [玩家]
    permission: friend.commands

  coin:
    description: 硬币系统命令
    usage: /<command> [add|remove|list|reload|pay] [玩家] [数量]
    permission: coin.commands

  shop:
    description: 商店系统
    usage: /<command> [admin]
    permission: shop.use

  market:
    description: 玩家市场
    usage: /<command> [页码]
    permission: market.use

  lottery:
    description: 抽奖系统
    usage: /<command>
    permission: lottery.use

  hub:
    description: 回城命令
    usage: /<command>
    permission: hub.use

  skill:
    description: 自杀命令
    usage: /<command>
    permission: skill.use

  sv:
    description: 隐身命令
    usage: /<command>
    permission: sunk.sv

  breakboard:
    description: 挖掘榜开关
    usage: /<command>
    permission: breakboard.use

  catconfig:
    description: 配置管理
    usage: /<command> set [lobby|skill] [参数]
    permission: mikucore.config

permissions:
  friend.commands:
    description: 允许使用好友命令
    default: true

  coin.commands:
    description: 允许使用硬币命令
    default: op

  shop.use:
    description: 允许使用商店
    default: true

  shop.admin:
    description: 允许管理商店
    default: op

  market.use:
    description: 允许使用玩家市场
    default: true

  lottery.use:
    description: 允许使用抽奖
    default: true

  hub.use:
    description: 允许使用回城命令
    default: true

  skill.use:
    description: 允许使用自杀命令
    default: true

  sunk.sv:
    description: 允许使用隐身命令
    default: op

  breakboard.use:
    description: 允许使用挖掘榜
    default: true

  mikucore.config:
    description: 允许修改插件配置
    default: op