name: MikuDreamCore
version: '1.2.008'
main: cn.mikudream.core.MikuDream
api-version: '1.21'
authors: [onea]
folia-supported: true
soft-depend: []
website: https://github.com/oneachina/SunkPlugin
commands:
  hub:
    description: hub
  skill:
    description: skill
  sconfig:
    description: sconfig
  sbreakboard:
    description: off & on the breakboard
    usage: /sbreakboard
  scoin:
    description: 查看scoin
    usage: /scoin
  sv:
    description: sv
    usage: /sv
  srf:
    description: srf
    usage: /srf


permissions:
  sunk.config:
    description: config
    default: op
  sunk.breakboard:
    description: breakboard
    default: true
  scoin.commands:
    description: 使用scoin命令的总权限
    default: true
  scoin.list:
    description: 使用list子命令
    default: true
  scoin.add:
    description: 使用add子命令
    default: op
  scoin.version:
    description: 使用version子命令
    default: true
  sunk.sv:
    description: sv
    default: op
  scoin.reload:
    description: 使用reload子命令
    default: op
  scoin.remove:
    description: 使用remove子命令
    default: op
